### ISSUE TITLE
Problem with sort by popularity search

### ISSUE THREAD

**Issue by Choiney** [Pixeval/Pixeval#256]
My search by popularity doesn't work when I search keywords. It does however work on my recommended tab. 

My account is premium if that is relevant.

**Comment by dylech30th** [comment]
The current version (which I wrote 1.5 years ago when I'm new to the language and the framework, and this is my first GUI project) does not detect the premium account, which is a severe design defect, it is fixed in the new version that I'm working on as you can track progress in the main branch, however, it may take some time because I'm a student, not a full-time freelancer, I can't spend all of my times on it, if you are urgent and does not care about the platform (mobile or PC), you can also try [pixez_flutter](https://github.com/Notsfsssf/pixez-flutter) on Android/iOS which is developed by one of my friends

**Comment by Poker-sang** [comment]
Fixed
