### ISSUE TITLE
Dark Mode when?

### ISSUE THREAD

**Issue by ojoiP** [Pixeval/Pixeval#335]
### The type of your suggestion

New feature

### Pixeval's version

WinUI3

### Description

Love the client, would love to know when Dark Mode is coming

**Comment by dylech30th** [comment]
Dark mode is built-in together as part of the default theme provided by WinUI 3. There is currently no viable way to directly download the archive of the WinUI 3 version since it is under development (slow development because I am subject to heavy pressure IRL which makes me busy), you are encouraged to build the source code yourself.

**Comment by Poker-sang** [comment]
Fixed
