### ISSUE TITLE
r18 content not available

### ISSUE THREAD

**Issue by Talos911** [Pixeval/Pixeval#521]
### Pixeval's version

WinUI3

### Description of the problem

As the title says. No r18 content is shown on the pixeval.It is enabled on my pixiv account 

### Screenshot

![Capturess](https://github.com/user-attachments/assets/8f85029c-7681-444a-8bd1-125cf3498ddc)

### Windows major version

Windows 10

**Comment by Talos911** [comment]
![Capturess](https://github.com/user-attachments/assets/e3045c50-2a7c-4b88-bc03-9587399ff3a4)

**Comment by Poker-sang** [comment]
If the R18 artwork is restricted, it will appear as follows, instead of simply not displaying the image (which is different from the AI generated artwork)

![image](https://github.com/user-attachments/assets/b28e7265-b699-4e74-a55b-bc8693fdb9f2)

You can test whether to restrict R18 by selecting the R18 list on the ranking page.

Or just open an R18 illustration in Pixeval via ID and if it shows the image then it's ok.

If the problem persists, maybe you're not logged into the same account on the pixiv and on Pixeval
