### ISSUE TITLE
Can't this program just use cache?

### ISSUE THREAD

**Issue by sombresu** [Pixeval/Pixeval#98]
Every time I scroll in my collection windows or reopen the page I've just visited seconds ago the thumbnails are gone and so the program keep redownloading them all over again and again each time. This program is heavy on resource, maybe one of the reason is because of this too.

**Comment by Rinacm** [comment]
the reason of heavily resources utilization is that there is a bug on data virtualization in StackPanel, and I can promise you fix this issue is the best way to solve this problem instead of  using cache. it has been fixed on my workstation but due to some unavoidable and unspeakable (family) reasons it cannot be updated now, I'm under heavily pressure on both body and spirit, and after all this things I will update it ASAP, so I beg your understanding

**Comment by Rinacm** [comment]
and the issue about data virtualization on StackPanel is because of the container has positive infinity desire height so the virtualizing logic cannot identify which element is out of view port so that it cannot virtualize any of the element.

**Comment by LasmGratel** [comment]
Performances has been optimized in recent WinUI3 version
